#############################################################################
# Makefile for building: QtSortingAlgorithms.app/Contents/MacOS/QtSortingAlgorithms
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  QtSortingAlgorithms.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile QtSortingAlgorithms.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/opt/local/share/qt5/mkspecs/macx-clang -I. -I. -I/opt/local/Library/Frameworks/QtOpenGL.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/opt/local/Library/Frameworks
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/opt/local/Library/Frameworks -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework QtNetwork -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = BubbleSorter.cpp \
		InsertionSorter.cpp \
		main.cpp \
		mainWindow.cpp \
		MergeSorter.cpp \
		QuickSorter.cpp \
		SortViewWidget.cpp \
		TimerWidget.cpp \
		vectoreditor.cpp \
		VectorSorter.cpp qrc_resources.cpp \
		moc_BubbleSorter.cpp \
		moc_mainWindow.cpp \
		moc_SortViewWidget.cpp \
		moc_TimerWidget.cpp \
		moc_vectoreditor.cpp \
		moc_VectorSorter.cpp
OBJECTS       = BubbleSorter.o \
		InsertionSorter.o \
		main.o \
		mainWindow.o \
		MergeSorter.o \
		QuickSorter.o \
		SortViewWidget.o \
		TimerWidget.o \
		vectoreditor.o \
		VectorSorter.o \
		qrc_resources.o \
		moc_BubbleSorter.o \
		moc_mainWindow.o \
		moc_SortViewWidget.o \
		moc_TimerWidget.o \
		moc_vectoreditor.o \
		moc_VectorSorter.o
DIST          = /opt/local/share/qt5/mkspecs/features/spec_pre.prf \
		/opt/local/share/qt5/mkspecs/qdevice.pri \
		/opt/local/share/qt5/mkspecs/features/device_config.prf \
		/opt/local/share/qt5/mkspecs/common/shell-unix.conf \
		/opt/local/share/qt5/mkspecs/common/unix.conf \
		/opt/local/share/qt5/mkspecs/common/mac.conf \
		/opt/local/share/qt5/mkspecs/common/macx.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base-mac.conf \
		/opt/local/share/qt5/mkspecs/common/clang.conf \
		/opt/local/share/qt5/mkspecs/common/clang-mac.conf \
		/opt/local/share/qt5/mkspecs/qconfig.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/share/qt5/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt5/mkspecs/features/qt_config.prf \
		/opt/local/share/qt5/mkspecs/macx-clang/qmake.conf \
		/opt/local/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/share/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt5/mkspecs/features/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/resolve_config.prf \
		/opt/local/share/qt5/mkspecs/features/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/c++11.prf \
		/opt/local/share/qt5/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt5/mkspecs/features/warn_on.prf \
		/opt/local/share/qt5/mkspecs/features/qt.prf \
		/opt/local/share/qt5/mkspecs/features/resources.prf \
		/opt/local/share/qt5/mkspecs/features/moc.prf \
		/opt/local/share/qt5/mkspecs/features/unix/opengl.prf \
		/opt/local/share/qt5/mkspecs/features/uic.prf \
		/opt/local/share/qt5/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt5/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt5/mkspecs/features/testcase_targets.prf \
		/opt/local/share/qt5/mkspecs/features/exceptions.prf \
		/opt/local/share/qt5/mkspecs/features/yacc.prf \
		/opt/local/share/qt5/mkspecs/features/lex.prf \
		QtSortingAlgorithms.pro BubbleSorter.cpp \
		InsertionSorter.cpp \
		main.cpp \
		mainWindow.cpp \
		MergeSorter.cpp \
		QuickSorter.cpp \
		SortViewWidget.cpp \
		TimerWidget.cpp \
		vectoreditor.cpp \
		VectorSorter.cpp
QMAKE_TARGET  = QtSortingAlgorithms
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QtSortingAlgorithms.app/Contents/MacOS/QtSortingAlgorithms

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QtSortingAlgorithms.app/Contents/PkgInfo QtSortingAlgorithms.app/Contents/Resources/empty.lproj QtSortingAlgorithms.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d QtSortingAlgorithms.app/Contents/MacOS/ || mkdir -p QtSortingAlgorithms.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtSortingAlgorithms.pro /opt/local/share/qt5/mkspecs/macx-clang/qmake.conf /opt/local/share/qt5/mkspecs/features/spec_pre.prf \
		/opt/local/share/qt5/mkspecs/qdevice.pri \
		/opt/local/share/qt5/mkspecs/features/device_config.prf \
		/opt/local/share/qt5/mkspecs/common/shell-unix.conf \
		/opt/local/share/qt5/mkspecs/common/unix.conf \
		/opt/local/share/qt5/mkspecs/common/mac.conf \
		/opt/local/share/qt5/mkspecs/common/macx.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base-mac.conf \
		/opt/local/share/qt5/mkspecs/common/clang.conf \
		/opt/local/share/qt5/mkspecs/common/clang-mac.conf \
		/opt/local/share/qt5/mkspecs/qconfig.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/share/qt5/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt5/mkspecs/features/qt_config.prf \
		/opt/local/share/qt5/mkspecs/macx-clang/qmake.conf \
		/opt/local/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/share/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt5/mkspecs/features/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/resolve_config.prf \
		/opt/local/share/qt5/mkspecs/features/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/c++11.prf \
		/opt/local/share/qt5/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt5/mkspecs/features/warn_on.prf \
		/opt/local/share/qt5/mkspecs/features/qt.prf \
		/opt/local/share/qt5/mkspecs/features/resources.prf \
		/opt/local/share/qt5/mkspecs/features/moc.prf \
		/opt/local/share/qt5/mkspecs/features/unix/opengl.prf \
		/opt/local/share/qt5/mkspecs/features/uic.prf \
		/opt/local/share/qt5/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt5/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt5/mkspecs/features/testcase_targets.prf \
		/opt/local/share/qt5/mkspecs/features/exceptions.prf \
		/opt/local/share/qt5/mkspecs/features/yacc.prf \
		/opt/local/share/qt5/mkspecs/features/lex.prf \
		QtSortingAlgorithms.pro \
		resources.qrc \
		/opt/local/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl \
		/opt/local/Library/Frameworks/QtWidgets.framework/QtWidgets.prl \
		/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl \
		/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl \
		/opt/local/Library/Frameworks/QtNetwork.framework/QtNetwork.prl \
		/opt/local/Library/Frameworks/QtSql.framework/QtSql.prl
	$(QMAKE) -o Makefile QtSortingAlgorithms.pro
/opt/local/share/qt5/mkspecs/features/spec_pre.prf:
/opt/local/share/qt5/mkspecs/qdevice.pri:
/opt/local/share/qt5/mkspecs/features/device_config.prf:
/opt/local/share/qt5/mkspecs/common/shell-unix.conf:
/opt/local/share/qt5/mkspecs/common/unix.conf:
/opt/local/share/qt5/mkspecs/common/mac.conf:
/opt/local/share/qt5/mkspecs/common/macx.conf:
/opt/local/share/qt5/mkspecs/common/gcc-base.conf:
/opt/local/share/qt5/mkspecs/common/gcc-base-mac.conf:
/opt/local/share/qt5/mkspecs/common/clang.conf:
/opt/local/share/qt5/mkspecs/common/clang-mac.conf:
/opt/local/share/qt5/mkspecs/qconfig.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/local/share/qt5/mkspecs/features/qt_functions.prf:
/opt/local/share/qt5/mkspecs/features/qt_config.prf:
/opt/local/share/qt5/mkspecs/macx-clang/qmake.conf:
/opt/local/share/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/local/share/qt5/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt5/mkspecs/features/default_pre.prf:
/opt/local/share/qt5/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt5/mkspecs/features/resolve_config.prf:
/opt/local/share/qt5/mkspecs/features/default_post.prf:
/opt/local/share/qt5/mkspecs/features/c++11.prf:
/opt/local/share/qt5/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt5/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt5/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt5/mkspecs/features/warn_on.prf:
/opt/local/share/qt5/mkspecs/features/qt.prf:
/opt/local/share/qt5/mkspecs/features/resources.prf:
/opt/local/share/qt5/mkspecs/features/moc.prf:
/opt/local/share/qt5/mkspecs/features/unix/opengl.prf:
/opt/local/share/qt5/mkspecs/features/uic.prf:
/opt/local/share/qt5/mkspecs/features/unix/thread.prf:
/opt/local/share/qt5/mkspecs/features/mac/rez.prf:
/opt/local/share/qt5/mkspecs/features/testcase_targets.prf:
/opt/local/share/qt5/mkspecs/features/exceptions.prf:
/opt/local/share/qt5/mkspecs/features/yacc.prf:
/opt/local/share/qt5/mkspecs/features/lex.prf:
QtSortingAlgorithms.pro:
resources.qrc:
/opt/local/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl:
/opt/local/Library/Frameworks/QtWidgets.framework/QtWidgets.prl:
/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl:
/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl:
/opt/local/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
/opt/local/Library/Frameworks/QtSql.framework/QtSql.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QtSortingAlgorithms.pro

qmake_all: FORCE

QtSortingAlgorithms.app/Contents/PkgInfo: 
	@test -d QtSortingAlgorithms.app/Contents || mkdir -p QtSortingAlgorithms.app/Contents
	@$(DEL_FILE) QtSortingAlgorithms.app/Contents/PkgInfo
	@echo "APPL????" >QtSortingAlgorithms.app/Contents/PkgInfo
QtSortingAlgorithms.app/Contents/Resources/empty.lproj: 
	@test -d QtSortingAlgorithms.app/Contents/Resources || mkdir -p QtSortingAlgorithms.app/Contents/Resources
	@touch QtSortingAlgorithms.app/Contents/Resources/empty.lproj
	
QtSortingAlgorithms.app/Contents/Info.plist: 
	@test -d QtSortingAlgorithms.app/Contents || mkdir -p QtSortingAlgorithms.app/Contents
	@$(DEL_FILE) QtSortingAlgorithms.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,teste.QtSortingAlgorithms,g" -e "s,@EXECUTABLE@,QtSortingAlgorithms,g" -e "s,@TYPEINFO@,????,g" /opt/local/share/qt5/mkspecs/macx-clang/Info.plist.app >QtSortingAlgorithms.app/Contents/Info.plist
dist: 
	@test -d .tmp/QtSortingAlgorithms1.0.0 || mkdir -p .tmp/QtSortingAlgorithms1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/QtSortingAlgorithms1.0.0/ && $(COPY_FILE) --parents resources.qrc resources.qrc .tmp/QtSortingAlgorithms1.0.0/ && $(COPY_FILE) --parents BubbleSorter.h InsertionSorter.h mainWindow.h MergeSorter.h QuickSorter.h SortViewWidget.h TimerWidget.h vectoreditor.h VectorSorter.h .tmp/QtSortingAlgorithms1.0.0/ && $(COPY_FILE) --parents BubbleSorter.cpp InsertionSorter.cpp main.cpp mainWindow.cpp MergeSorter.cpp QuickSorter.cpp SortViewWidget.cpp TimerWidget.cpp vectoreditor.cpp VectorSorter.cpp .tmp/QtSortingAlgorithms1.0.0/ && (cd `dirname .tmp/QtSortingAlgorithms1.0.0` && $(TAR) QtSortingAlgorithms1.0.0.tar QtSortingAlgorithms1.0.0 && $(COMPRESS) QtSortingAlgorithms1.0.0.tar) && $(MOVE) `dirname .tmp/QtSortingAlgorithms1.0.0`/QtSortingAlgorithms1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtSortingAlgorithms1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r QtSortingAlgorithms.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp qrc_resources.cpp
qrc_resources.cpp: resources.qrc
	/opt/local/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

qrc_resources.cpp: resources.qrc
	/opt/local/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_BubbleSorter.cpp moc_mainWindow.cpp moc_SortViewWidget.cpp moc_TimerWidget.cpp moc_vectoreditor.cpp moc_VectorSorter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_BubbleSorter.cpp moc_mainWindow.cpp moc_SortViewWidget.cpp moc_TimerWidget.cpp moc_vectoreditor.cpp moc_VectorSorter.cpp
moc_BubbleSorter.cpp: VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		BubbleSorter.h
	/opt/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Users/wachs/Dropbox/Codes/qtComVim -I/Users/wachs/Dropbox/Codes/qtComVim -I/opt/local/Library/Frameworks/QtOpenGL.framework/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Headers -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/Library/Frameworks BubbleSorter.h -o moc_BubbleSorter.cpp

moc_mainWindow.cpp: /opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QCalendarWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		SortViewWidget.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPaintEvent \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qevent.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPainter \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qpainter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QRect \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsProxyWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QResource \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qresource.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		BubbleSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QSlider \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qslider.h \
		MergeSorter.h \
		vectoreditor.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QSize \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDateTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdatetime.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QCoreApplication \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QApplication \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		InsertionSorter.h \
		QuickSorter.h \
		TimerWidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTimer \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qtimer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QPluginLoader \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		mainWindow.h
	/opt/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Users/wachs/Dropbox/Codes/qtComVim -I/Users/wachs/Dropbox/Codes/qtComVim -I/opt/local/Library/Frameworks/QtOpenGL.framework/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Headers -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/Library/Frameworks mainWindow.h -o moc_mainWindow.cpp

moc_SortViewWidget.cpp: /opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPaintEvent \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qevent.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPainter \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qpainter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QRect \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsProxyWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QResource \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qresource.h \
		SortViewWidget.h
	/opt/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Users/wachs/Dropbox/Codes/qtComVim -I/Users/wachs/Dropbox/Codes/qtComVim -I/opt/local/Library/Frameworks/QtOpenGL.framework/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Headers -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/Library/Frameworks SortViewWidget.h -o moc_SortViewWidget.cpp

moc_TimerWidget.cpp: /opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTimer \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qtimer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdatetime.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		TimerWidget.h
	/opt/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Users/wachs/Dropbox/Codes/qtComVim -I/Users/wachs/Dropbox/Codes/qtComVim -I/opt/local/Library/Frameworks/QtOpenGL.framework/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Headers -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/Library/Frameworks TimerWidget.h -o moc_TimerWidget.cpp

moc_vectoreditor.cpp: /opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QSize \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qsize.h \
		vectoreditor.h
	/opt/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Users/wachs/Dropbox/Codes/qtComVim -I/Users/wachs/Dropbox/Codes/qtComVim -I/opt/local/Library/Frameworks/QtOpenGL.framework/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Headers -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/Library/Frameworks vectoreditor.h -o moc_vectoreditor.cpp

moc_VectorSorter.cpp: /opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		VectorSorter.h
	/opt/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Users/wachs/Dropbox/Codes/qtComVim -I/Users/wachs/Dropbox/Codes/qtComVim -I/opt/local/Library/Frameworks/QtOpenGL.framework/Headers -I/opt/local/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/Library/Frameworks/QtNetwork.framework/Headers -I/opt/local/Library/Frameworks/QtSql.framework/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Headers -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/Library/Frameworks VectorSorter.h -o moc_VectorSorter.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

BubbleSorter.o: BubbleSorter.cpp BubbleSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BubbleSorter.o BubbleSorter.cpp

InsertionSorter.o: InsertionSorter.cpp InsertionSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InsertionSorter.o InsertionSorter.cpp

main.o: main.cpp /opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QApplication \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainWindow.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QCalendarWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		SortViewWidget.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPaintEvent \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qevent.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPainter \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qpainter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QRect \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsProxyWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QResource \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qresource.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		BubbleSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QSlider \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qslider.h \
		MergeSorter.h \
		vectoreditor.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QSize \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDateTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdatetime.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QCoreApplication \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		InsertionSorter.h \
		QuickSorter.h \
		TimerWidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTimer \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qtimer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QPluginLoader \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscrollarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cpp mainWindow.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QCalendarWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		SortViewWidget.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPaintEvent \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qevent.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPainter \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qpainter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QRect \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsProxyWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QResource \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qresource.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		BubbleSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QSlider \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qslider.h \
		MergeSorter.h \
		vectoreditor.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QSize \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDateTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdatetime.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QCoreApplication \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QApplication \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		InsertionSorter.h \
		QuickSorter.h \
		TimerWidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTimer \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qtimer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QPluginLoader \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscrollarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

MergeSorter.o: MergeSorter.cpp MergeSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MergeSorter.o MergeSorter.cpp

QuickSorter.o: QuickSorter.cpp QuickSorter.h \
		VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuickSorter.o QuickSorter.cpp

SortViewWidget.o: SortViewWidget.cpp SortViewWidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPaintEvent \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qevent.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/QPainter \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers/qpainter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QRect \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QGraphicsProxyWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QResource \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qresource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SortViewWidget.o SortViewWidget.cpp

TimerWidget.o: TimerWidget.cpp TimerWidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTimer \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qtimer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTime \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdatetime.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimerWidget.o TimerWidget.cpp

vectoreditor.o: vectoreditor.cpp vectoreditor.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableView \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QLabel \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QSize \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qsize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vectoreditor.o vectoreditor.cpp

VectorSorter.o: VectorSorter.cpp VectorSorter.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QObject \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QVector \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QThread \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qthread.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/QDebug \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VectorSorter.o VectorSorter.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_BubbleSorter.o: moc_BubbleSorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BubbleSorter.o moc_BubbleSorter.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

moc_SortViewWidget.o: moc_SortViewWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SortViewWidget.o moc_SortViewWidget.cpp

moc_TimerWidget.o: moc_TimerWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TimerWidget.o moc_TimerWidget.cpp

moc_vectoreditor.o: moc_vectoreditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vectoreditor.o moc_vectoreditor.cpp

moc_VectorSorter.o: moc_VectorSorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VectorSorter.o moc_VectorSorter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

