# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "c:\Program Files (x86)\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "c:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\gwachs\Codes\QtSortingAlgorithms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\gwachs\Codes\QtSortingAlgorithms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"c:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\gwachs\Codes\QtSortingAlgorithms\CMakeFiles C:\Users\gwachs\Codes\QtSortingAlgorithms\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\gwachs\Codes\QtSortingAlgorithms\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QtSortingAlgorithms

# Build rule for target.
QtSortingAlgorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 QtSortingAlgorithms
.PHONY : QtSortingAlgorithms

# fast build rule for target.
QtSortingAlgorithms/fast:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/build
.PHONY : QtSortingAlgorithms/fast

#=============================================================================
# Target rules for targets named QtSortingAlgorithms_automoc

# Build rule for target.
QtSortingAlgorithms_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 QtSortingAlgorithms_automoc
.PHONY : QtSortingAlgorithms_automoc

# fast build rule for target.
QtSortingAlgorithms_automoc/fast:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms_automoc.dir\build.make CMakeFiles/QtSortingAlgorithms_automoc.dir/build
.PHONY : QtSortingAlgorithms_automoc/fast

BubbleSorter.obj: BubbleSorter.cpp.obj
.PHONY : BubbleSorter.obj

# target to build an object file
BubbleSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/BubbleSorter.cpp.obj
.PHONY : BubbleSorter.cpp.obj

BubbleSorter.i: BubbleSorter.cpp.i
.PHONY : BubbleSorter.i

# target to preprocess a source file
BubbleSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/BubbleSorter.cpp.i
.PHONY : BubbleSorter.cpp.i

BubbleSorter.s: BubbleSorter.cpp.s
.PHONY : BubbleSorter.s

# target to generate assembly for a file
BubbleSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/BubbleSorter.cpp.s
.PHONY : BubbleSorter.cpp.s

InsertionSorter.obj: InsertionSorter.cpp.obj
.PHONY : InsertionSorter.obj

# target to build an object file
InsertionSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/InsertionSorter.cpp.obj
.PHONY : InsertionSorter.cpp.obj

InsertionSorter.i: InsertionSorter.cpp.i
.PHONY : InsertionSorter.i

# target to preprocess a source file
InsertionSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/InsertionSorter.cpp.i
.PHONY : InsertionSorter.cpp.i

InsertionSorter.s: InsertionSorter.cpp.s
.PHONY : InsertionSorter.s

# target to generate assembly for a file
InsertionSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/InsertionSorter.cpp.s
.PHONY : InsertionSorter.cpp.s

MergeSorter.obj: MergeSorter.cpp.obj
.PHONY : MergeSorter.obj

# target to build an object file
MergeSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/MergeSorter.cpp.obj
.PHONY : MergeSorter.cpp.obj

MergeSorter.i: MergeSorter.cpp.i
.PHONY : MergeSorter.i

# target to preprocess a source file
MergeSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/MergeSorter.cpp.i
.PHONY : MergeSorter.cpp.i

MergeSorter.s: MergeSorter.cpp.s
.PHONY : MergeSorter.s

# target to generate assembly for a file
MergeSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/MergeSorter.cpp.s
.PHONY : MergeSorter.cpp.s

QtSortingAlgorithms_automoc.obj: QtSortingAlgorithms_automoc.cpp.obj
.PHONY : QtSortingAlgorithms_automoc.obj

# target to build an object file
QtSortingAlgorithms_automoc.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/QtSortingAlgorithms_automoc.cpp.obj
.PHONY : QtSortingAlgorithms_automoc.cpp.obj

QtSortingAlgorithms_automoc.i: QtSortingAlgorithms_automoc.cpp.i
.PHONY : QtSortingAlgorithms_automoc.i

# target to preprocess a source file
QtSortingAlgorithms_automoc.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/QtSortingAlgorithms_automoc.cpp.i
.PHONY : QtSortingAlgorithms_automoc.cpp.i

QtSortingAlgorithms_automoc.s: QtSortingAlgorithms_automoc.cpp.s
.PHONY : QtSortingAlgorithms_automoc.s

# target to generate assembly for a file
QtSortingAlgorithms_automoc.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/QtSortingAlgorithms_automoc.cpp.s
.PHONY : QtSortingAlgorithms_automoc.cpp.s

QuickSorter.obj: QuickSorter.cpp.obj
.PHONY : QuickSorter.obj

# target to build an object file
QuickSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/QuickSorter.cpp.obj
.PHONY : QuickSorter.cpp.obj

QuickSorter.i: QuickSorter.cpp.i
.PHONY : QuickSorter.i

# target to preprocess a source file
QuickSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/QuickSorter.cpp.i
.PHONY : QuickSorter.cpp.i

QuickSorter.s: QuickSorter.cpp.s
.PHONY : QuickSorter.s

# target to generate assembly for a file
QuickSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/QuickSorter.cpp.s
.PHONY : QuickSorter.cpp.s

SortViewWidget.obj: SortViewWidget.cpp.obj
.PHONY : SortViewWidget.obj

# target to build an object file
SortViewWidget.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/SortViewWidget.cpp.obj
.PHONY : SortViewWidget.cpp.obj

SortViewWidget.i: SortViewWidget.cpp.i
.PHONY : SortViewWidget.i

# target to preprocess a source file
SortViewWidget.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/SortViewWidget.cpp.i
.PHONY : SortViewWidget.cpp.i

SortViewWidget.s: SortViewWidget.cpp.s
.PHONY : SortViewWidget.s

# target to generate assembly for a file
SortViewWidget.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/SortViewWidget.cpp.s
.PHONY : SortViewWidget.cpp.s

TimerWidget.obj: TimerWidget.cpp.obj
.PHONY : TimerWidget.obj

# target to build an object file
TimerWidget.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/TimerWidget.cpp.obj
.PHONY : TimerWidget.cpp.obj

TimerWidget.i: TimerWidget.cpp.i
.PHONY : TimerWidget.i

# target to preprocess a source file
TimerWidget.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/TimerWidget.cpp.i
.PHONY : TimerWidget.cpp.i

TimerWidget.s: TimerWidget.cpp.s
.PHONY : TimerWidget.s

# target to generate assembly for a file
TimerWidget.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/TimerWidget.cpp.s
.PHONY : TimerWidget.cpp.s

VectorSorter.obj: VectorSorter.cpp.obj
.PHONY : VectorSorter.obj

# target to build an object file
VectorSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/VectorSorter.cpp.obj
.PHONY : VectorSorter.cpp.obj

VectorSorter.i: VectorSorter.cpp.i
.PHONY : VectorSorter.i

# target to preprocess a source file
VectorSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/VectorSorter.cpp.i
.PHONY : VectorSorter.cpp.i

VectorSorter.s: VectorSorter.cpp.s
.PHONY : VectorSorter.s

# target to generate assembly for a file
VectorSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/VectorSorter.cpp.s
.PHONY : VectorSorter.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/main.cpp.s
.PHONY : main.cpp.s

mainWindow.obj: mainWindow.cpp.obj
.PHONY : mainWindow.obj

# target to build an object file
mainWindow.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/mainWindow.cpp.obj
.PHONY : mainWindow.cpp.obj

mainWindow.i: mainWindow.cpp.i
.PHONY : mainWindow.i

# target to preprocess a source file
mainWindow.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/mainWindow.cpp.i
.PHONY : mainWindow.cpp.i

mainWindow.s: mainWindow.cpp.s
.PHONY : mainWindow.s

# target to generate assembly for a file
mainWindow.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/mainWindow.cpp.s
.PHONY : mainWindow.cpp.s

moc_BubbleSorter.obj: moc_BubbleSorter.cpp.obj
.PHONY : moc_BubbleSorter.obj

# target to build an object file
moc_BubbleSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_BubbleSorter.cpp.obj
.PHONY : moc_BubbleSorter.cpp.obj

moc_BubbleSorter.i: moc_BubbleSorter.cpp.i
.PHONY : moc_BubbleSorter.i

# target to preprocess a source file
moc_BubbleSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_BubbleSorter.cpp.i
.PHONY : moc_BubbleSorter.cpp.i

moc_BubbleSorter.s: moc_BubbleSorter.cpp.s
.PHONY : moc_BubbleSorter.s

# target to generate assembly for a file
moc_BubbleSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_BubbleSorter.cpp.s
.PHONY : moc_BubbleSorter.cpp.s

moc_SortViewWidget.obj: moc_SortViewWidget.cpp.obj
.PHONY : moc_SortViewWidget.obj

# target to build an object file
moc_SortViewWidget.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_SortViewWidget.cpp.obj
.PHONY : moc_SortViewWidget.cpp.obj

moc_SortViewWidget.i: moc_SortViewWidget.cpp.i
.PHONY : moc_SortViewWidget.i

# target to preprocess a source file
moc_SortViewWidget.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_SortViewWidget.cpp.i
.PHONY : moc_SortViewWidget.cpp.i

moc_SortViewWidget.s: moc_SortViewWidget.cpp.s
.PHONY : moc_SortViewWidget.s

# target to generate assembly for a file
moc_SortViewWidget.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_SortViewWidget.cpp.s
.PHONY : moc_SortViewWidget.cpp.s

moc_TimerWidget.obj: moc_TimerWidget.cpp.obj
.PHONY : moc_TimerWidget.obj

# target to build an object file
moc_TimerWidget.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_TimerWidget.cpp.obj
.PHONY : moc_TimerWidget.cpp.obj

moc_TimerWidget.i: moc_TimerWidget.cpp.i
.PHONY : moc_TimerWidget.i

# target to preprocess a source file
moc_TimerWidget.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_TimerWidget.cpp.i
.PHONY : moc_TimerWidget.cpp.i

moc_TimerWidget.s: moc_TimerWidget.cpp.s
.PHONY : moc_TimerWidget.s

# target to generate assembly for a file
moc_TimerWidget.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_TimerWidget.cpp.s
.PHONY : moc_TimerWidget.cpp.s

moc_VectorSorter.obj: moc_VectorSorter.cpp.obj
.PHONY : moc_VectorSorter.obj

# target to build an object file
moc_VectorSorter.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_VectorSorter.cpp.obj
.PHONY : moc_VectorSorter.cpp.obj

moc_VectorSorter.i: moc_VectorSorter.cpp.i
.PHONY : moc_VectorSorter.i

# target to preprocess a source file
moc_VectorSorter.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_VectorSorter.cpp.i
.PHONY : moc_VectorSorter.cpp.i

moc_VectorSorter.s: moc_VectorSorter.cpp.s
.PHONY : moc_VectorSorter.s

# target to generate assembly for a file
moc_VectorSorter.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_VectorSorter.cpp.s
.PHONY : moc_VectorSorter.cpp.s

moc_mainWindow.obj: moc_mainWindow.cpp.obj
.PHONY : moc_mainWindow.obj

# target to build an object file
moc_mainWindow.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_mainWindow.cpp.obj
.PHONY : moc_mainWindow.cpp.obj

moc_mainWindow.i: moc_mainWindow.cpp.i
.PHONY : moc_mainWindow.i

# target to preprocess a source file
moc_mainWindow.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_mainWindow.cpp.i
.PHONY : moc_mainWindow.cpp.i

moc_mainWindow.s: moc_mainWindow.cpp.s
.PHONY : moc_mainWindow.s

# target to generate assembly for a file
moc_mainWindow.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_mainWindow.cpp.s
.PHONY : moc_mainWindow.cpp.s

moc_vectoreditor.obj: moc_vectoreditor.cpp.obj
.PHONY : moc_vectoreditor.obj

# target to build an object file
moc_vectoreditor.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_vectoreditor.cpp.obj
.PHONY : moc_vectoreditor.cpp.obj

moc_vectoreditor.i: moc_vectoreditor.cpp.i
.PHONY : moc_vectoreditor.i

# target to preprocess a source file
moc_vectoreditor.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_vectoreditor.cpp.i
.PHONY : moc_vectoreditor.cpp.i

moc_vectoreditor.s: moc_vectoreditor.cpp.s
.PHONY : moc_vectoreditor.s

# target to generate assembly for a file
moc_vectoreditor.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/moc_vectoreditor.cpp.s
.PHONY : moc_vectoreditor.cpp.s

qrc_resources.obj: qrc_resources.cpp.obj
.PHONY : qrc_resources.obj

# target to build an object file
qrc_resources.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/qrc_resources.cpp.obj
.PHONY : qrc_resources.cpp.obj

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

vectoreditor.obj: vectoreditor.cpp.obj
.PHONY : vectoreditor.obj

# target to build an object file
vectoreditor.cpp.obj:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/vectoreditor.cpp.obj
.PHONY : vectoreditor.cpp.obj

vectoreditor.i: vectoreditor.cpp.i
.PHONY : vectoreditor.i

# target to preprocess a source file
vectoreditor.cpp.i:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/vectoreditor.cpp.i
.PHONY : vectoreditor.cpp.i

vectoreditor.s: vectoreditor.cpp.s
.PHONY : vectoreditor.s

# target to generate assembly for a file
vectoreditor.cpp.s:
	$(MAKE) -f CMakeFiles\QtSortingAlgorithms.dir\build.make CMakeFiles/QtSortingAlgorithms.dir/vectoreditor.cpp.s
.PHONY : vectoreditor.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... QtSortingAlgorithms
	@echo ... QtSortingAlgorithms_automoc
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... BubbleSorter.obj
	@echo ... BubbleSorter.i
	@echo ... BubbleSorter.s
	@echo ... InsertionSorter.obj
	@echo ... InsertionSorter.i
	@echo ... InsertionSorter.s
	@echo ... MergeSorter.obj
	@echo ... MergeSorter.i
	@echo ... MergeSorter.s
	@echo ... QtSortingAlgorithms_automoc.obj
	@echo ... QtSortingAlgorithms_automoc.i
	@echo ... QtSortingAlgorithms_automoc.s
	@echo ... QuickSorter.obj
	@echo ... QuickSorter.i
	@echo ... QuickSorter.s
	@echo ... SortViewWidget.obj
	@echo ... SortViewWidget.i
	@echo ... SortViewWidget.s
	@echo ... TimerWidget.obj
	@echo ... TimerWidget.i
	@echo ... TimerWidget.s
	@echo ... VectorSorter.obj
	@echo ... VectorSorter.i
	@echo ... VectorSorter.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... mainWindow.obj
	@echo ... mainWindow.i
	@echo ... mainWindow.s
	@echo ... moc_BubbleSorter.obj
	@echo ... moc_BubbleSorter.i
	@echo ... moc_BubbleSorter.s
	@echo ... moc_SortViewWidget.obj
	@echo ... moc_SortViewWidget.i
	@echo ... moc_SortViewWidget.s
	@echo ... moc_TimerWidget.obj
	@echo ... moc_TimerWidget.i
	@echo ... moc_TimerWidget.s
	@echo ... moc_VectorSorter.obj
	@echo ... moc_VectorSorter.i
	@echo ... moc_VectorSorter.s
	@echo ... moc_mainWindow.obj
	@echo ... moc_mainWindow.i
	@echo ... moc_mainWindow.s
	@echo ... moc_vectoreditor.obj
	@echo ... moc_vectoreditor.i
	@echo ... moc_vectoreditor.s
	@echo ... qrc_resources.obj
	@echo ... qrc_resources.i
	@echo ... qrc_resources.s
	@echo ... vectoreditor.obj
	@echo ... vectoreditor.i
	@echo ... vectoreditor.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

