# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/QtSortingAlgorithms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/QtSortingAlgorithms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/QtSortingAlgorithms/CMakeFiles /tmp/QtSortingAlgorithms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/QtSortingAlgorithms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QtSortingAlgorithms

# Build rule for target.
QtSortingAlgorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QtSortingAlgorithms
.PHONY : QtSortingAlgorithms

# fast build rule for target.
QtSortingAlgorithms/fast:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/build
.PHONY : QtSortingAlgorithms/fast

#=============================================================================
# Target rules for targets named QtSortingAlgorithms_automoc

# Build rule for target.
QtSortingAlgorithms_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QtSortingAlgorithms_automoc
.PHONY : QtSortingAlgorithms_automoc

# fast build rule for target.
QtSortingAlgorithms_automoc/fast:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms_automoc.dir/build.make CMakeFiles/QtSortingAlgorithms_automoc.dir/build
.PHONY : QtSortingAlgorithms_automoc/fast

BubbleSorter.o: BubbleSorter.cpp.o
.PHONY : BubbleSorter.o

# target to build an object file
BubbleSorter.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/BubbleSorter.cpp.o
.PHONY : BubbleSorter.cpp.o

BubbleSorter.i: BubbleSorter.cpp.i
.PHONY : BubbleSorter.i

# target to preprocess a source file
BubbleSorter.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/BubbleSorter.cpp.i
.PHONY : BubbleSorter.cpp.i

BubbleSorter.s: BubbleSorter.cpp.s
.PHONY : BubbleSorter.s

# target to generate assembly for a file
BubbleSorter.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/BubbleSorter.cpp.s
.PHONY : BubbleSorter.cpp.s

InsertionSorter.o: InsertionSorter.cpp.o
.PHONY : InsertionSorter.o

# target to build an object file
InsertionSorter.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/InsertionSorter.cpp.o
.PHONY : InsertionSorter.cpp.o

InsertionSorter.i: InsertionSorter.cpp.i
.PHONY : InsertionSorter.i

# target to preprocess a source file
InsertionSorter.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/InsertionSorter.cpp.i
.PHONY : InsertionSorter.cpp.i

InsertionSorter.s: InsertionSorter.cpp.s
.PHONY : InsertionSorter.s

# target to generate assembly for a file
InsertionSorter.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/InsertionSorter.cpp.s
.PHONY : InsertionSorter.cpp.s

MergeSorter.o: MergeSorter.cpp.o
.PHONY : MergeSorter.o

# target to build an object file
MergeSorter.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/MergeSorter.cpp.o
.PHONY : MergeSorter.cpp.o

MergeSorter.i: MergeSorter.cpp.i
.PHONY : MergeSorter.i

# target to preprocess a source file
MergeSorter.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/MergeSorter.cpp.i
.PHONY : MergeSorter.cpp.i

MergeSorter.s: MergeSorter.cpp.s
.PHONY : MergeSorter.s

# target to generate assembly for a file
MergeSorter.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/MergeSorter.cpp.s
.PHONY : MergeSorter.cpp.s

QtSortingAlgorithms_automoc.o: QtSortingAlgorithms_automoc.cpp.o
.PHONY : QtSortingAlgorithms_automoc.o

# target to build an object file
QtSortingAlgorithms_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/QtSortingAlgorithms_automoc.cpp.o
.PHONY : QtSortingAlgorithms_automoc.cpp.o

QtSortingAlgorithms_automoc.i: QtSortingAlgorithms_automoc.cpp.i
.PHONY : QtSortingAlgorithms_automoc.i

# target to preprocess a source file
QtSortingAlgorithms_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/QtSortingAlgorithms_automoc.cpp.i
.PHONY : QtSortingAlgorithms_automoc.cpp.i

QtSortingAlgorithms_automoc.s: QtSortingAlgorithms_automoc.cpp.s
.PHONY : QtSortingAlgorithms_automoc.s

# target to generate assembly for a file
QtSortingAlgorithms_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/QtSortingAlgorithms_automoc.cpp.s
.PHONY : QtSortingAlgorithms_automoc.cpp.s

QuickSorter.o: QuickSorter.cpp.o
.PHONY : QuickSorter.o

# target to build an object file
QuickSorter.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/QuickSorter.cpp.o
.PHONY : QuickSorter.cpp.o

QuickSorter.i: QuickSorter.cpp.i
.PHONY : QuickSorter.i

# target to preprocess a source file
QuickSorter.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/QuickSorter.cpp.i
.PHONY : QuickSorter.cpp.i

QuickSorter.s: QuickSorter.cpp.s
.PHONY : QuickSorter.s

# target to generate assembly for a file
QuickSorter.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/QuickSorter.cpp.s
.PHONY : QuickSorter.cpp.s

SortViewWidget.o: SortViewWidget.cpp.o
.PHONY : SortViewWidget.o

# target to build an object file
SortViewWidget.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/SortViewWidget.cpp.o
.PHONY : SortViewWidget.cpp.o

SortViewWidget.i: SortViewWidget.cpp.i
.PHONY : SortViewWidget.i

# target to preprocess a source file
SortViewWidget.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/SortViewWidget.cpp.i
.PHONY : SortViewWidget.cpp.i

SortViewWidget.s: SortViewWidget.cpp.s
.PHONY : SortViewWidget.s

# target to generate assembly for a file
SortViewWidget.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/SortViewWidget.cpp.s
.PHONY : SortViewWidget.cpp.s

TimerWidget.o: TimerWidget.cpp.o
.PHONY : TimerWidget.o

# target to build an object file
TimerWidget.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/TimerWidget.cpp.o
.PHONY : TimerWidget.cpp.o

TimerWidget.i: TimerWidget.cpp.i
.PHONY : TimerWidget.i

# target to preprocess a source file
TimerWidget.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/TimerWidget.cpp.i
.PHONY : TimerWidget.cpp.i

TimerWidget.s: TimerWidget.cpp.s
.PHONY : TimerWidget.s

# target to generate assembly for a file
TimerWidget.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/TimerWidget.cpp.s
.PHONY : TimerWidget.cpp.s

VectorSorter.o: VectorSorter.cpp.o
.PHONY : VectorSorter.o

# target to build an object file
VectorSorter.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/VectorSorter.cpp.o
.PHONY : VectorSorter.cpp.o

VectorSorter.i: VectorSorter.cpp.i
.PHONY : VectorSorter.i

# target to preprocess a source file
VectorSorter.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/VectorSorter.cpp.i
.PHONY : VectorSorter.cpp.i

VectorSorter.s: VectorSorter.cpp.s
.PHONY : VectorSorter.s

# target to generate assembly for a file
VectorSorter.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/VectorSorter.cpp.s
.PHONY : VectorSorter.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/main.cpp.s
.PHONY : main.cpp.s

mainWindow.o: mainWindow.cpp.o
.PHONY : mainWindow.o

# target to build an object file
mainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/mainWindow.cpp.o
.PHONY : mainWindow.cpp.o

mainWindow.i: mainWindow.cpp.i
.PHONY : mainWindow.i

# target to preprocess a source file
mainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/mainWindow.cpp.i
.PHONY : mainWindow.cpp.i

mainWindow.s: mainWindow.cpp.s
.PHONY : mainWindow.s

# target to generate assembly for a file
mainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/mainWindow.cpp.s
.PHONY : mainWindow.cpp.s

qrc_resources.o: qrc_resources.cpp.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/qrc_resources.cpp.o
.PHONY : qrc_resources.cpp.o

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

vectoreditor.o: vectoreditor.cpp.o
.PHONY : vectoreditor.o

# target to build an object file
vectoreditor.cpp.o:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/vectoreditor.cpp.o
.PHONY : vectoreditor.cpp.o

vectoreditor.i: vectoreditor.cpp.i
.PHONY : vectoreditor.i

# target to preprocess a source file
vectoreditor.cpp.i:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/vectoreditor.cpp.i
.PHONY : vectoreditor.cpp.i

vectoreditor.s: vectoreditor.cpp.s
.PHONY : vectoreditor.s

# target to generate assembly for a file
vectoreditor.cpp.s:
	$(MAKE) -f CMakeFiles/QtSortingAlgorithms.dir/build.make CMakeFiles/QtSortingAlgorithms.dir/vectoreditor.cpp.s
.PHONY : vectoreditor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... QtSortingAlgorithms"
	@echo "... QtSortingAlgorithms_automoc"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BubbleSorter.o"
	@echo "... BubbleSorter.i"
	@echo "... BubbleSorter.s"
	@echo "... InsertionSorter.o"
	@echo "... InsertionSorter.i"
	@echo "... InsertionSorter.s"
	@echo "... MergeSorter.o"
	@echo "... MergeSorter.i"
	@echo "... MergeSorter.s"
	@echo "... QtSortingAlgorithms_automoc.o"
	@echo "... QtSortingAlgorithms_automoc.i"
	@echo "... QtSortingAlgorithms_automoc.s"
	@echo "... QuickSorter.o"
	@echo "... QuickSorter.i"
	@echo "... QuickSorter.s"
	@echo "... SortViewWidget.o"
	@echo "... SortViewWidget.i"
	@echo "... SortViewWidget.s"
	@echo "... TimerWidget.o"
	@echo "... TimerWidget.i"
	@echo "... TimerWidget.s"
	@echo "... VectorSorter.o"
	@echo "... VectorSorter.i"
	@echo "... VectorSorter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainWindow.o"
	@echo "... mainWindow.i"
	@echo "... mainWindow.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
	@echo "... vectoreditor.o"
	@echo "... vectoreditor.i"
	@echo "... vectoreditor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

