/* This file is autogenerated, do not edit*/
#include "moc_BubbleSorter.cpp"
#include "moc_SortViewWidget.cpp"
#include "moc_TimerWidget.cpp"
#include "moc_VectorSorter.cpp"
#include "moc_mainWindow.cpp"
#include "moc_vectoreditor.cpp"
